import React, { useState } from 'react';
import { Modal, Pressable, ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { useStore } from '../../services/store';
import { VehicleIcon } from '../../components/VehicleSelector';
import { Button, IconButton, styles, usePalette } from '../../components/ui';
export default function Vehicles() {
  const p = usePalette(), { vehicles, addVehicle, vehicleLocked, navigationOptions } = useStore();
  const [adding, setAdding] = useState(false);
  return <SafeAreaView style={{ flex: 1, backgroundColor: p.bg }}><ScrollView contentContainerStyle={{ padding: 24, gap: 16, width: '100%', maxWidth: 700, alignSelf: 'center', paddingBottom: 90 }}><View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}><Text style={[styles.title, { color: p.text }]}>Vehicles</Text><IconButton label="Add vehicle" icon="add" disabled={vehicleLocked} onPress={() => setAdding(true)} /></View><Text style={{ color: p.muted }}>Your garage. Choose which vehicle to ride in Where to.</Text>{vehicles.map(v => <Pressable key={v.id} accessibilityRole="button" accessibilityLabel={`Edit ${v.name}`} onPress={() => router.push(`/scooter/${v.id}`)} style={[styles.card, { backgroundColor: p.card, flexDirection: 'row', alignItems: 'center' }]}><VehicleIcon vehicle={v} size={64} /><View style={{ flex: 1 }}><Text style={{ color: p.text, fontWeight: '700', fontSize: 18 }}>{v.name}</Text><Text style={{ color: p.muted, fontSize: 12 }}>{v.kind === 'ebike' ? 'E-bike' : 'E-scooter'} · Hardware {(v.maxSpeed / (navigationOptions.unit === 'mi' ? 1.609344 : 1)).toFixed(0)} · Riding {(v.ridingLimit / (navigationOptions.unit === 'mi' ? 1.609344 : 1)).toFixed(0)} {navigationOptions.unit === 'mi' ? 'mph' : 'km/h'}</Text></View><Ionicons name="chevron-forward" color={p.muted} size={22} /></Pressable>)}{vehicleLocked && <Text style={{ color: p.muted }}>Finish your current ride before editing vehicles.</Text>}</ScrollView><Modal visible={adding} transparent animationType="fade" onRequestClose={() => setAdding(false)}><View style={{ flex: 1, backgroundColor: '#0007', justifyContent: 'center', padding: 24 }}><View style={[styles.card, { backgroundColor: p.bg, width: '100%', maxWidth: 420, alignSelf: 'center' }]}><View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}><Text style={{ color: p.text, fontSize: 22, fontWeight: '700' }}>Add a vehicle</Text><IconButton label="Close vehicle type chooser" icon="close" onPress={() => setAdding(false)} /></View>{(['escooter', 'ebike'] as const).map(kind => <Button key={kind} title={kind === 'ebike' ? 'E-bike' : 'E-scooter'} icon={kind === 'ebike' ? 'bicycle' : 'flash-outline'} disabled={vehicleLocked} onPress={() => { const id = addVehicle(kind); setAdding(false); if (id) router.push(`/scooter/${id}`); }} />)}</View></View></Modal></SafeAreaView>;
}
