import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Text, View, SectionList, Platform, Alert } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useFocusEffect } from 'expo-router';
import RideInsights from '../components/RideInsights';
import RoutePreview from '../components/RoutePreview';
import { pickTrack, shareTrack, shareRideData } from '../services/files';
import { RecordedRide } from '../core/recordings';
import { recordedRides, rideSamples, deleteRecordedRide } from '../services/rideHistory';
import { Route } from '../core/types';
import { Button, IconButton, styles, usePalette } from '../components/ui';
import { useStore } from '../services/store';
import { packs, download, deletePack, listen, unlisten, PackView } from '../services/offline';
import { offlineEnabled } from '../components/mapConfig';
import { distanceLeft } from '../core/rideView';
import { batteryLabel } from '../core/vehicles';
import { estimate, minutes } from '../core/eta';
export default function Library() {
  const p = usePalette(), { saved, save, ready, vehicleLocked, selected, select, setRoutes, remove, profile, navigationOptions } = useStore();
  const [regions, setRegions] = useState<PackView[]>([]), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const [history, setHistory] = useState<RecordedRide[]>([]);
  useFocusEffect(useCallback(() => { let cancelled = false; const refresh = () => { void recordedRides().then(r => { if (!cancelled) setHistory(r); }).catch(e => { if (!cancelled) setError(e.message); }); }; refresh(); const timer = setInterval(refresh, 5000); return () => { cancelled = true; clearInterval(timer); }; }, []));

  const attached = useRef<string[]>([]), mounted = useRef(true);
  const refresh = useCallback(async () => {
    const all = await packs(); if (!mounted.current) return; setRegions(all);
    for (const r of all) if (!attached.current.includes(r.id)) { attached.current.push(r.id); await listen(r.id, (_, status) => { if (mounted.current) setRegions(v => v.map(x => x.id === status.id ? { ...x, percentage: status.percentage, bytes: status.completedResourceSize, state: status.state } : x)); }, msg => { if (mounted.current) setError(msg); }); }
  }, []);
  useFocusEffect(useCallback(() => { void refresh().catch(e => setError(e.message)); }, [refresh]));
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; attached.current.forEach(unlisten); }; }, []);
  async function run(fn: () => Promise<unknown>) { setError(''); try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }
  function deleteRegion(id: string) {
    const act = () => void run(async () => { unlisten(id); attached.current = attached.current.filter(x => x !== id); await deletePack(id); await refresh(); });
    if (Platform.OS === 'web') { if (window.confirm('Delete this downloaded map region?')) act(); } else Alert.alert('Delete map region?', 'You can download it again later.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: act }]);
  }
  function savedCard(r: Route) { const e = estimate(r, profile); return <View key={r.id} style={[styles.card, { backgroundColor: p.card, marginBottom: 18 }]}><RoutePreview route={r} /><Text style={{ color: p.text, fontWeight: '700', fontSize: 18 }}>{r.name}</Text><Text style={{ color: p.muted }}>Start · {r.startLabel || positionLabel(r.coordinates[0])}</Text><Text style={{ color: p.muted }}>Arrival · {r.endLabel || positionLabel(r.coordinates.at(-1)!)}</Text><Text style={{ color: p.muted }}>{distanceLeft(e.meters, navigationOptions.unit)} · {minutes(e.seconds)} · {batteryLabel(e.meters, profile)} · {r.steps.length ? `${r.steps.length} instructions` : 'Track only'}</Text><View style={{ flexDirection: 'row', gap: 10 }}><View style={{ flex: 1 }}><Button title="Open" icon="navigate-outline" disabled={vehicleLocked} onPress={() => { setRoutes([r]); select(r); router.navigate('/'); }} /></View><IconButton label="Export route as GPX" icon="share-outline" onPress={() => void run(() => shareTrack(r.coordinates))} /><IconButton label="Delete saved route" icon="trash-outline" onPress={() => confirmDelete(() => void run(() => remove(r.id)))} /></View></View>; }
  function rideCard(r: RecordedRide) { return <View key={r.id} style={[styles.card, { backgroundColor: p.card, marginBottom: 18 }]}>{r.preview.length > 1 && <RoutePreview route={recordedRoute(r)} />}<Text style={{ color: p.text, fontWeight: '700', fontSize: 18 }}>{r.name}</Text><Text style={{ color: p.muted }}>{new Date(r.startedAt).toLocaleString()} · {r.vehicle.name}</Text><Text style={{ color: p.muted }}>Start · {r.startLabel}{r.start ? ` · ${positionLabel(r.start)}` : ''}</Text><Text style={{ color: p.muted }}>Arrival · {r.endLabel}{r.end ? ` · ${positionLabel(r.end)}` : ''}</Text><Text style={{ color: p.muted }}>{distanceLeft(r.meters, navigationOptions.unit)} · {r.samples} timestamped fixes · {r.status}{r.endedAt ? ` · ${minutes((r.endedAt - r.startedAt) / 1000)}` : ''}</Text><View style={{ flexDirection: 'row', gap: 10 }}><View style={{ flex: 1 }}><Button title="Export GPX" icon="share-outline" secondary disabled={!r.samples || r.status === 'recording'} onPress={() => void run(async () => shareRideData(r, await rideSamples(r), 'gpx'))} /></View><IconButton label="Export full sensor data as JSON" icon="code-download-outline" disabled={!r.samples || r.status === 'recording'} onPress={() => void run(async () => shareRideData(r, await rideSamples(r), 'json'))} /><IconButton label="Delete recorded ride" icon="trash-outline" disabled={r.status === 'recording'} onPress={() => confirmDelete(() => void run(async () => { await deleteRecordedRide(r); setHistory(await recordedRides()); }))} /></View></View>; }
  return <SafeAreaView edges={['top']} style={{ flex: 1, backgroundColor: p.bg }}><SectionList<Route | RecordedRide> sections={[{ title: 'Saved routes', data: saved }, { title: 'Recorded rides', data: history }]} stickySectionHeadersEnabled={false} initialNumToRender={2} maxToRenderPerBatch={2} windowSize={3} keyExtractor={item => item.id} renderItem={({ item }) => 'coordinates' in item ? savedCard(item) : rideCard(item)} renderSectionHeader={({ section }) => <View style={{ gap: 12, marginVertical: 18 }}><Text style={{ color: p.text, fontSize: 20, fontWeight: '800' }}>{section.title}</Text>{!section.data.length && <Text style={{ color: p.muted }}>{section.title === 'Saved routes' ? 'Import a GPX or save a planned route from Explore.' : 'Future GPS rides appear here when Record Rides is enabled in Settings. Simulations are never recorded.'}</Text>}{section.title === 'Recorded rides' && <RideInsights rides={history} unit={navigationOptions.unit} />}</View>} contentContainerStyle={{ padding: 22, gap: 18, width: '100%', maxWidth: 780, alignSelf: 'center', paddingBottom: 90 }} ListHeaderComponent={<View style={{ gap: 18 }}>
    <Text style={[styles.title, { color: p.text }]}>Library</Text><Text style={[styles.subtitle, { color: p.muted }]}>Your routes, imported GPX tracks and recorded rides stay on this device.</Text>
    <Button title="Import GPX to Library" icon="add-outline" secondary disabled={!ready} onPress={() => void run(async () => { const r = await pickTrack(); if (r) await save(r); })} />
    </View>} ListFooterComponent={<View style={{ gap: 18 }}>
    <Text style={{ color: p.text, fontSize: 20, fontWeight: '800' }}>Downloaded maps</Text>
    <View style={[styles.card, { backgroundColor: p.card }]}><Text style={{ color: p.text, fontWeight: '700' }}>Map region for your selected route</Text><Text style={{ color: p.muted, lineHeight: 20 }}>{Platform.OS === 'web' ? 'Downloads are available in the native app.' : !offlineEnabled ? 'Downloads need an offline-licensed map provider configured during setup.' : 'Downloads the route bounding box plus a small margin, zooms 10–16. Download on Wi-Fi; size depends on the region.'}</Text><Button title={busy ? 'Creating download…' : 'Download selected region'} disabled={busy || !selected || !offlineEnabled || Platform.OS === 'web'} icon="download-outline" onPress={() => void run(async () => { setBusy(true); try { await download(selected!, () => { void refresh().catch(e => setError(e.message)); }, setError); await refresh(); } finally { setBusy(false); } })} /></View>
    {regions.map(r => <View key={r.id} style={[styles.card, { backgroundColor: p.card }]}><Text style={{ color: p.text, fontWeight: '700' }}>{r.name}</Text><Text style={{ color: p.muted }}>{r.state} · {r.percentage.toFixed(0)}% · {(r.bytes / 1e6).toFixed(1)} MB downloaded</Text><View style={{ height: 5, backgroundColor: p.line, borderRadius: 5 }}><View style={{ height: 5, width: `${Math.min(100, r.percentage)}%`, backgroundColor: p.accent, borderRadius: 5 }} /></View><View style={{ flexDirection: 'row', gap: 10 }}>{r.state !== 'complete' && <Button title={r.state === 'active' ? 'Pause' : 'Resume'} secondary onPress={() => void run(async () => { if (r.state === 'active') await r.pack.pause(); else await r.pack.resume(); await refresh(); })} />}<IconButton label="Delete downloaded map" icon="trash-outline" onPress={() => deleteRegion(r.id)} /></View></View>)}
    {!!error && <Text style={{ color: '#C75A36' }}>{error}</Text>}
    <Text style={{ color: p.muted, lineHeight: 21 }}>Android uses OpenFreeMap with MapLibre. Enable Use downloadable maps in Settings to automatically use a completed region covering your current location or the whole route; otherwise iOS uses Apple Maps. Apple Maps does not expose app-managed region downloads. Offline maps contain map resources, not a routing graph. Saved-route guidance works without new route requests. Planning and rerouting require a connection; on-device route calculation is future work.</Text>
  </View>} /></SafeAreaView>;
}

function positionLabel(p: [number, number]) { return `${p[1].toFixed(5)}, ${p[0].toFixed(5)}`; }
function confirmDelete(action: () => void) { if (Platform.OS === 'web') { if (window.confirm('Delete this item from Library?')) action(); } else Alert.alert('Delete from Library?', 'This removes the local record.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: action }]); }
function recordedRoute(r: RecordedRide): Route { return { id: `preview-${r.id}`, name: r.name, kind: 'track', coordinates: r.preview, steps: [], details: {}, source: 'gpx', warnings: [] }; }
