import React, { useState } from 'react';
import { Platform, Text, View, ScrollView, Switch, Linking } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useStore } from '../services/store';
import { Button, Field, styles, usePalette } from '../components/ui';
import VehicleSelector, { VehicleIcon } from '../components/VehicleSelector';
import { pickVehiclePhoto } from '../services/files';
import { rangeValue, rangeKm } from '../core/vehicles';
import { Profile } from '../core/types';
function NumberField({ label, value, min, max, onSave }: { label: string; value: number; min: number; max: number; onSave(v: number): void }) {
  const [text, setText] = useState(String(value)), [error, setError] = useState(''); const p = usePalette();
  return <View style={{ gap: 4 }}><Field label={label} value={text} onChangeText={setText} keyboardType="decimal-pad" onBlur={() => { if (text === String(value)) return; const v = Number(text.replace(',', '.')); if (!Number.isFinite(v) || v < min || v > max) { setError(`Choose ${min}–${max}.`); setText(String(value)); } else { setError(''); onSave(v); } }} />{!!error && <Text style={{ color: '#C75A36' }}>{error}</Text>}<Text style={{ color: p.muted, fontSize: 11 }}>Range {min}–{max}</Text></View>;
}
function RangeField() {
  const { profile, updateProfile, navigationOptions } = useStore(), p = usePalette();
  const initial = profile.rangeKm ? rangeValue(profile.rangeKm, navigationOptions.unit).toFixed(2).replace(/\.?0+$/, '') : '';
  const [text, setText] = useState(initial), [error, setError] = useState('');
  return <View style={{ gap: 6 }}><Field label={`FULL-CHARGE RANGE · ${navigationOptions.unit === 'mi' ? 'MILES' : 'KM'}`} value={text} onChangeText={setText} placeholder="Unknown — enter your real-world range" keyboardType="decimal-pad" onBlur={() => { if (text === initial) return; if (!text.trim()) { updateProfile({ rangeKm: null }); setError(''); return; } const n = Number(text.replace(',', '.')), km = rangeKm(n, navigationOptions.unit); if (Number.isFinite(n) && n > 0 && km <= 10000) { updateProfile({ rangeKm: km }); setError(''); } else setError('Enter a positive range, up to 10,000 km.'); }} />{!!error && <Text style={{ color: '#C75A36' }}>{error}</Text>}<Text style={{ color: p.muted, fontSize: 12 }}>Trip battery use is distance ÷ your full-charge range. This is an approximation, not a live battery reading. Assist level, hills, speed, weather and battery health change range.</Text></View>;
}
export default function Vehicles() {
  const p = usePalette(), { profile, vehicles, updateProfile, addVehicle, deleteVehicle, vehicleLocked, navigationOptions } = useStore();
  const [photoError, setPhotoError] = useState('');
  const fields: { key: keyof Profile; label: string; min: number; max: number }[] = [
    { key: 'maxSpeed', label: 'HARDWARE MAX · KM/H', min: 1, max: 60 }, { key: 'ridingLimit', label: 'LOCAL RIDING LIMIT · KM/H', min: 1, max: 60 }, { key: 'cruiseFactor', label: 'CRUISE FRACTION · 0.8 = 80%', min: .2, max: 1 }, { key: 'acceleration', label: 'ACCELERATION · M/S²', min: .1, max: 4 }, { key: 'stopDelay', label: 'DELAY PER MANEUVER · SECONDS', min: 0, max: 120 },
  ];
  return <SafeAreaView edges={['top']} style={{ flex: 1, backgroundColor: p.bg }}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ padding: 22, gap: 18, width: '100%', maxWidth: 780, alignSelf: 'center' }}>
    <Text style={[styles.title, { color: p.text }]}>Made for your ride.</Text><Text style={[styles.subtitle, { color: p.muted }]}>Set your e-scooter or e-bike’s capability. Keep the local riding limit separate: your ETA uses the lower speed.</Text>
    <VehicleSelector />
    {vehicleLocked && <Text style={{ color: p.muted }}>Finish your current ride before changing vehicle settings.</Text>}
    <View pointerEvents={vehicleLocked ? 'none' : 'auto'} accessibilityElementsHidden={vehicleLocked} importantForAccessibility={vehicleLocked ? 'no-hide-descendants' : 'auto'} style={{ gap: 18, opacity: vehicleLocked ? .5 : 1 }}>
    <View style={{ flexDirection: 'row', gap: 10 }}><View style={{ flex: 1 }}><Button title="Add e-scooter" secondary onPress={() => addVehicle('escooter')} /></View><View style={{ flex: 1 }}><Button title="Add e-bike" secondary onPress={() => addVehicle('ebike')} /></View></View>
    <View style={[styles.card, { backgroundColor: p.card }]}><View style={{ flexDirection: 'row', gap: 12, alignItems: 'center' }}><VehicleIcon vehicle={profile} size={64} /><Text style={{ color: p.text, fontSize: 22, fontWeight: '700' }}>{profile.kind === 'ebike' ? 'E-bike' : 'E-scooter'}</Text></View><Field label="VEHICLE NAME" maxLength={80} value={profile.name} onChangeText={name => updateProfile({ name })} />{fields.slice(0, 2).map(f => <NumberField key={`${profile.id}-${f.key}-${profile[f.key]}-${navigationOptions.unit}`} label={f.label.replace('KM/H', navigationOptions.unit === 'mi' ? 'MPH' : 'KM/H')} value={Number(((profile[f.key] as number) / (navigationOptions.unit === 'mi' ? 1.609344 : 1)).toFixed(2))} min={Number((f.min / (navigationOptions.unit === 'mi' ? 1.609344 : 1)).toFixed(2))} max={Number((f.max / (navigationOptions.unit === 'mi' ? 1.609344 : 1)).toFixed(2))} onSave={v => updateProfile({ [f.key]: Math.max(1, Math.min(60, v * (navigationOptions.unit === 'mi' ? 1.609344 : 1))) })} />)}</View>
    <View style={[styles.card, { backgroundColor: p.card }]}><Text style={{ color: p.text, fontWeight: '700' }}>Range & battery estimate</Text><RangeField key={`${profile.id}-${navigationOptions.unit}-${profile.rangeKm}`} /></View>
    <View style={[styles.card, { backgroundColor: p.card }]}><Text style={{ color: p.text, fontWeight: '700' }}>Icon or picture</Text><View style={{ flexDirection: 'row', gap: 8, flexWrap: 'wrap' }}>{['🛴', '🚲', '⚡', '🛵', '🚴', '🔋'].map(icon => <Button key={icon} title={icon} secondary onPress={() => updateProfile({ icon, photo: null })} />)}</View><Field label="CUSTOM ICON · EMOJI OR SYMBOL" value={profile.icon} maxLength={32} onChangeText={icon => updateProfile({ icon: icon || (profile.kind === 'ebike' ? '🚲' : '🛴'), photo: null })} /><Button title={Platform.OS === 'web' ? 'Choose vehicle picture' : 'Choose from photo library'} secondary icon="image-outline" onPress={() => { const id = profile.id; setPhotoError(''); void pickVehiclePhoto().then(photo => { if (photo) updateProfile({ photo }, id); }).catch(e => setPhotoError(e.message)); }} />{profile.photo && <Button title="Remove picture" secondary onPress={() => updateProfile({ photo: null })} />}{!!photoError && <Text accessibilityRole="alert" style={{ color: '#C75A36' }}>{photoError}</Text>}<Button title="Browse public vehicle pictures ↗" secondary onPress={() => void Linking.openURL(`https://commons.wikimedia.org/w/index.php?search=${profile.kind === 'ebike' ? 'electric+bicycle' : 'electric+kick+scooter'}&title=Special:MediaSearch&type=image`).catch(() => setPhotoError('Could not open the image catalogue.'))} /><Text style={{ color: p.muted, fontSize: 12 }}>Wikimedia Commons opens in your browser. Download a suitable picture and import it here (photos are resized on mobile; web imports PNG, JPEG or WebP under 1 MB). Check the image’s licence and attribution. Pictures stay on this device; they are not uploaded.</Text></View>
    <View style={[styles.card, { backgroundColor: p.card }]}><Text style={{ color: p.text, fontWeight: '700' }}>ETA tuning</Text>{fields.slice(2).map(f => <NumberField key={`${profile.id}-${f.key}-${profile[f.key]}`} label={f.label} value={profile[f.key] as number} min={f.min} max={f.max} onSave={v => updateProfile({ [f.key]: v })} />)}</View>
    <View style={[styles.card, { backgroundColor: p.card }]}>{(['voice', 'motion'] as const).map(key => <View key={key} style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><View style={{ flex: 1 }}><Text style={{ color: p.text, fontWeight: '700' }}>{key === 'voice' ? 'Spoken directions' : 'Motion readings'}</Text><Text style={{ color: p.muted, fontSize: 12 }}>{key === 'voice' ? 'For routes with turn instructions' : 'Accelerometer and gyroscope during GPS rides'}</Text></View><Switch accessibilityLabel={key === 'voice' ? 'Spoken directions' : 'Motion readings'} value={profile[key]} onValueChange={v => updateProfile({ [key]: v })} trackColor={{ true: p.accent }} /></View>)}</View>
    <Text style={{ color: p.muted, lineHeight: 21 }}>The practical ETA models cruise speed, slower segments and maneuver delays. It does not predict traffic, gradients or weather. Motion readings are diagnostics, not crash detection or dead reckoning.</Text>
    <Text style={{ color: p.muted, lineHeight: 21 }}>New scooters start at 25 km/h. E-bike assistance speeds vary by model and market: 25, 32 or 45 km/h are common examples. Set your own capability and a riding limit appropriate for local rules. A route does not verify vehicle eligibility; check access and signs.</Text>
    <Button title="Delete this vehicle" secondary disabled={vehicles.length <= 1} onPress={() => deleteVehicle(profile.id)} /><Text style={{ color: p.muted, fontSize: 12 }}>Keep at least one vehicle. Deleting a vehicle does not delete your saved routes.</Text>
    </View>
  </ScrollView></SafeAreaView>;
}
