import React from 'react';
import { ScrollView, View, Text } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button, styles, usePalette } from '../components/ui';
import { useStore } from '../services/store';
export default function Settings() {
  const p = usePalette(), { navigationOptions: n, updateNavigationOptions } = useStore();
  return <SafeAreaView style={{ flex: 1, backgroundColor: p.bg }}><ScrollView contentContainerStyle={{ padding: 24, gap: 20, width: '100%', maxWidth: 700, alignSelf: 'center' }}><Text style={[styles.title, { color: p.text }]}>Settings</Text><View style={[styles.card, { backgroundColor: p.card }]}><Text style={{ color: p.text, fontSize: 18, fontWeight: '700' }}>Distance & speed units</Text><View style={{ flexDirection: 'row', gap: 10 }}><View style={{ flex: 1 }}><Button title="Kilometres · km/h" secondary={n.unit !== 'km'} onPress={() => updateNavigationOptions({ unit: 'km' })} /></View><View style={{ flex: 1 }}><Button title="Miles · mph" secondary={n.unit !== 'mi'} onPress={() => updateNavigationOptions({ unit: 'mi' })} /></View></View><Text style={{ color: p.muted }}>Applies throughout the app. Vehicle range and speed inputs follow these units too.</Text></View><View style={[styles.card, { backgroundColor: p.card }]}><Text style={{ color: p.text, fontSize: 18, fontWeight: '700' }}>Navigation view</Text><Button title={n.tilted ? '3D perspective on' : '2D flat map'} secondary onPress={() => updateNavigationOptions({ tilted: !n.tilted })} /><Button title={n.compass ? 'Use device compass when available' : 'Use travel direction'} secondary onPress={() => updateNavigationOptions({ compass: !n.compass })} /><Text style={{ color: p.muted }}>Web follows GPS course or route direction. Device compass needs a native build and good calibration.</Text></View><Text style={{ color: p.muted, lineHeight: 20 }}>Address search and route planning use Photon and Valhalla public services unless a GraphHopper server key is configured. Searches and endpoints are sent to these providers. Imported GPX stays on your device unless you explicitly plan a new route from its endpoints. Scheduled ETA never predicts traffic.</Text></ScrollView></SafeAreaView>;
}
