import { useStore } from '../services/store';
import { searchPlaces } from '../core/places';
import React, { useRef, useState } from 'react';
import { Keyboard, TextInput, View, Text, Pressable } from 'react-native';
import { Button, IconButton, usePalette, styles } from './ui';
import { Coord } from '../core/types';
import { searchAddresses, AddressResult } from '../services/api';
export default function EndpointPicker({ label, value, onChange, onSelect, onMap, onLocation, onFocus, showLocation = true, disabled = false }: { label: string; value: string; onChange(v: string): void; onSelect(label: string, coordinate: Coord): void; onMap(): void; onLocation?(): void; disabled?: boolean; onFocus?(): void; showLocation?: boolean }) {
  const { places, addPlace } = useStore();
  const p = usePalette(), [browsePlaces,setBrowsePlaces]=useState(false), [results, setResults] = useState<AddressResult[]>([]), [focused, setFocused] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const savedMatches = focused ? searchPlaces(places, browsePlaces || value === 'Current location' ? '' : value) : [];
  const searchId = useRef(0), input = useRef<TextInput>(null);
  function invalidate() { searchId.current++; setResults([]); setBusy(false); setError(''); }
  function dismiss() { input.current?.blur(); Keyboard.dismiss(); setFocused(false); setBrowsePlaces(false); }
  async function search() { const id = ++searchId.current; setBusy(true); setError(''); setResults([]); try { const found = await searchAddresses(value); if (id !== searchId.current) return; setResults(found); if (!found.length) setError('No matching address. Add a city or choose on the map.'); } catch (e) { if (id === searchId.current) setError(e instanceof Error ? e.message : String(e)); } finally { if (id === searchId.current) setBusy(false); } }
  return <View style={{ gap: 8 }}><Text style={{ color: p.muted, fontSize: 12, fontWeight: '700' }}>{label.toUpperCase()}</Text><View style={{ flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: 16, paddingRight: 4, backgroundColor: p.card, borderWidth: 1, borderColor: p.line }}><TextInput ref={input} accessibilityLabel={label} placeholder="Address, place or coordinates" placeholderTextColor={p.muted} value={value} editable={!disabled} onFocus={() => { setFocused(true); onFocus?.(); }} onChangeText={v => { invalidate(); onChange(v); }} onSubmitEditing={() => void search()} returnKeyType="search" style={[styles.field, { flex: 1, minWidth: 0, color: p.text, borderWidth: 0 }]} /><IconButton label={busy ? `Searching ${label}` : `Search ${label}`} icon="search" disabled={disabled || busy || value.trim().length < 3} onPress={() => void search()} /><IconButton label={`Browse saved places for ${label}`} icon="bookmark-outline" disabled={disabled} onPress={()=>{setFocused(true);onFocus?.();setBrowsePlaces(v=>!v);}} /><IconButton label={`Pick ${label} on map`} icon="map-outline" disabled={disabled} onPress={() => { invalidate(); dismiss(); onMap(); }} /></View>
    {focused && showLocation && onLocation && <Button title="Use my location" secondary disabled={disabled} icon="locate" onPress={() => { invalidate(); dismiss(); onLocation(); }} />}
    {savedMatches.length > 0 && <Text style={{color:p.muted,fontSize:12,fontWeight:'700'}}>SAVED PLACES</Text>}
    {savedMatches.map(r=><Pressable key={r.id} accessibilityRole="button" accessibilityLabel={`Choose saved place ${r.name}`} onPress={()=>{invalidate();dismiss();onSelect(r.address,r.coordinate);}} style={{padding:12,borderRadius:16,backgroundColor:p.card,gap:4}}><Text numberOfLines={1} style={{color:p.text,fontWeight:'700'}}>{r.name}</Text><Text numberOfLines={2} style={{color:p.muted,fontSize:12}}>{r.address}</Text></Pressable>)}
    {results.map(r => <View key={`${r.label}-${r.coordinate}`} style={{flexDirection:'row',alignItems:'center',gap:4,backgroundColor:p.card,borderRadius:16,padding:10}}><Pressable accessibilityRole="button" accessibilityLabel={r.label} disabled={disabled} onPress={() => { invalidate(); dismiss(); onSelect(r.label, r.coordinate); }} style={{flex:1,gap:4}}><Text numberOfLines={2} style={{color:p.text,fontWeight:'700',fontSize:16}}>{r.name}</Text><Text style={{color:p.muted,fontSize:12,lineHeight:18}}>{r.address}</Text></Pressable><IconButton label={`Save ${r.name} to places`} icon="bookmark-outline" disabled={places.some(p=>p.address===r.label)} onPress={()=>addPlace({name:r.name,address:r.label,coordinate:r.coordinate})} /></View>)}
    {!!error && <Text accessibilityRole="alert" style={{ color: '#C75A36' }}>{error}</Text>}
  </View>;
}
