import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Text, View, SectionList, Platform, Alert, Modal, KeyboardAvoidingView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useFocusEffect } from 'expo-router';
import RideInsights from '../components/RideInsights';
import RoutePreview from '../components/RoutePreview';
import { pickTrack, shareTrack, shareRideData } from '../services/files';
import { RecordedRide } from '../core/recordings';
import { recordedRides, rideSamples, deleteRecordedRide } from '../services/rideHistory';
import { Route , Coord } from '../core/types';
import { Button, Field, IconButton, styles, usePalette } from '../components/ui';
import { useStore } from '../services/store';
import { packs, download, deletePack, resumePack, listen, unlisten, PackView } from '../services/offline';
import { downloadStyle } from '../services/mapSettings';
import { distanceLeft } from '../core/rideView';
import { batteryLabel } from '../core/vehicles';
import { estimate, minutes } from '../core/eta';
import RideMap from './RideMap';
import EndpointPicker from './EndpointPicker';
import ActionMenu, { MenuAction } from './ActionMenu';
import { journeyTitle } from '../core/places';
export default function Library({ section }: { section: string }) {
  const offlineEnabled=!!downloadStyle();
  const p = usePalette(), { saved, save, ready, vehicleLocked, selected, select, setRoutes, remove, profile, navigationOptions, places, addPlace, deletePlace, renamePlace, requestJourney } = useStore();
  const [regions, setRegions] = useState<PackView[]>([]), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const [placeMap,setPlaceMap]=useState(false), [rename,setRename]=useState<{id:string;name:string}|null>(null);
  const [actions, setActions] = useState<MenuAction[] | null>(null), [placeName, setPlaceName] = useState(''), [address, setAddress] = useState(''), [placePoint, setPlacePoint] = useState<Coord | null>(null);
  const [history, setHistory] = useState<RecordedRide[]>([]);
  useFocusEffect(useCallback(() => { let cancelled = false; const refresh = () => { void recordedRides().then(r => { if (!cancelled) setHistory(r); }).catch(e => { if (!cancelled) setError(e.message); }); }; refresh(); const timer = setInterval(refresh, 5000); return () => { cancelled = true; clearInterval(timer); }; }, []));

  const attached = useRef<string[]>([]), mounted = useRef(true);
  const refresh = useCallback(async () => {
    const all = await packs(); if (!mounted.current) return; setRegions(all);
    for (const r of all) if (!attached.current.includes(r.id)) { attached.current.push(r.id); await listen(r.id, (_, status) => { if (mounted.current) setRegions(v => v.map(x => x.id === status.id ? { ...x, percentage: status.percentage, bytes: status.completedResourceSize, state: status.state } : x)); }, msg => { if (mounted.current) setError(msg); }); }
  }, []);
  useFocusEffect(useCallback(() => { void refresh().catch(e => setError(e.message)); }, [refresh]));
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; attached.current.forEach(unlisten); }; }, []);
  async function run(fn: () => Promise<unknown>) { setError(''); try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }
  function deleteRegion(id: string) {
    const act = () => void run(async () => { unlisten(id); attached.current = attached.current.filter(x => x !== id); await deletePack(id); await refresh(); });
    if (Platform.OS === 'web') { if (window.confirm('Delete this downloaded map region?')) act(); } else Alert.alert('Delete map region?', 'You can download it again later.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: act }]);
  }
  function savedCard(r: Route) { const e = estimate(r, profile); return <View key={r.id} style={[styles.card, { backgroundColor: p.card, marginBottom: 18 }]}><RoutePreview route={r} /><Text style={{ color: p.text, fontWeight: '700', fontSize: 18 }} numberOfLines={1}>{journeyTitle(r.startLabel, r.endLabel, r.name, r.savedAt)}</Text><Text style={{ color: p.muted }}>Start · {r.startLabel || positionLabel(r.coordinates[0])}</Text><Text style={{ color: p.muted }}>Arrival · {r.endLabel || positionLabel(r.coordinates.at(-1)!)}</Text><Text style={{ color: p.muted }}>{distanceLeft(e.meters, navigationOptions.unit)} · {minutes(e.seconds)} · {batteryLabel(e.meters, profile)} · {r.steps.length ? `${r.steps.length} instructions` : 'Track only'}</Text><View style={{ flexDirection: 'row', gap: 10 }}><View style={{ flex: 1 }}><Button title="Open" icon="navigate-outline" disabled={vehicleLocked} onPress={() => { setRoutes([r]); select(r); router.navigate('/'); }} /></View><IconButton label="Export route as GPX" icon="share-outline" onPress={() => void run(() => shareTrack(r.coordinates))} /><IconButton label="Delete saved route" icon="trash-outline" onPress={() => confirmDelete(() => void run(() => remove(r.id)))} /></View></View>; }
  function rideCard(r: RecordedRide) { return <View key={r.id} style={[styles.card, { backgroundColor: p.card, marginBottom: 18 }]}>{r.preview.length > 1 && <RoutePreview route={recordedRoute(r)} />}<Text style={{ color: p.text, fontWeight: '700', fontSize: 18 }} numberOfLines={1}>{journeyTitle(r.startLabel, r.endLabel, r.name, r.startedAt)}</Text><Text style={{ color: p.muted }}>{new Date(r.startedAt).toLocaleString()} · {r.vehicle.name}</Text><Text style={{ color: p.muted }}>Start · {r.startLabel}{r.start ? ` · ${positionLabel(r.start)}` : ''}</Text><Text style={{ color: p.muted }}>Arrival · {r.endLabel}{r.end ? ` · ${positionLabel(r.end)}` : ''}</Text><Text style={{ color: p.muted }}>{distanceLeft(r.meters, navigationOptions.unit)} · {r.samples} timestamped fixes · {r.status}{r.endedAt ? ` · ${minutes((r.endedAt - r.startedAt) / 1000)}` : ''}</Text><View style={{ flexDirection: 'row', gap: 10 }}><View style={{ flex: 1 }}><Button title="Start again" icon="navigate-outline" disabled={vehicleLocked || !r.start || !r.end || r.status === 'recording'} onPress={() => { requestJourney({start:r.start!,end:r.end!,startLabel:r.startLabel,endLabel:r.endLabel,requestedAt:Date.now()}); router.navigate('/'); }} /></View><IconButton label="Share recorded ride" icon="share-outline" disabled={!r.samples || r.status === 'recording'} onPress={() => { const share = (format: 'gpx' | 'json') => void run(async () => shareRideData(r, await rideSamples(r), format)); if (!navigationOptions.developerMode) share('gpx'); else setActions([{title:'Export GPX',icon:'share-outline',onPress:()=>share('gpx')},{title:'Export JSON',icon:'code-outline',onPress:()=>share('json')}]); }} /><IconButton label="Delete recorded ride" icon="trash-outline" disabled={r.status === 'recording'} onPress={() => confirmDelete(() => void run(async () => { await deleteRecordedRide(r); setHistory(await recordedRides()); }))} /></View></View>; }
  return <SafeAreaView edges={['top']} style={{ flex: 1, backgroundColor: p.bg }}><SectionList<Route | RecordedRide> sections={section === 'routes' ? [{ title: 'Saved Routes', data: saved }] : section === 'rides' ? [{ title: 'Recorded Rides', data: history }] : []} stickySectionHeadersEnabled={false} initialNumToRender={2} maxToRenderPerBatch={2} windowSize={3} keyExtractor={item => item.id} renderItem={({ item }) => 'coordinates' in item ? savedCard(item) : rideCard(item)} renderSectionHeader={({ section }) => <View style={{ gap: 12, marginVertical: 18 }}><Text style={{ color: p.text, fontSize: 20, fontWeight: '800' }}>{section.title}</Text>{!section.data.length && <Text style={{ color: p.muted }}>{section.title === 'Saved Routes' ? 'Import a GPX or save a planned route from Explore.' : 'Future GPS rides appear here when Record Rides is enabled in Settings. Simulations are never recorded.'}</Text>}{section.title === 'Recorded Rides' && <RideInsights rides={history} unit={navigationOptions.unit} />}</View>} contentContainerStyle={{ padding: 22, gap: 18, width: '100%', maxWidth: 780, alignSelf: 'center', paddingBottom: 90 }} ListHeaderComponent={<View style={{ gap: 18 }}>
    <View style={{flexDirection:'row',gap:12,alignItems:'center'}}><IconButton label="Back to Library" icon="chevron-back" onPress={()=>router.replace('/offline')} /><Text style={[styles.title, { color: p.text }]}>{section === 'places' ? 'Saved Places' : section === 'routes' ? 'Saved Routes' : section === 'rides' ? 'Recorded Rides' : 'Downloaded Maps'}</Text></View><Text style={[styles.subtitle, { color: p.muted }]}>Your routes, imported GPX tracks and recorded rides stay on this device.</Text>
    {section === 'places' && <><Field label="Place name" value={placeName} onChangeText={setPlaceName} /><EndpointPicker label="Place address" value={address} onChange={v=>{setAddress(v);setPlacePoint(null);}} onSelect={(label,c)=>{setAddress(label);setPlacePoint(c);if(!placeName)setPlaceName(label.split(',')[0]);}} onMap={()=>setPlaceMap(true)} /><Button title="Save place" icon="bookmark-outline" disabled={!placePoint || !placeName.trim()} onPress={()=>{addPlace({name:placeName.trim(),address,coordinate:placePoint!});setPlaceName('');setAddress('');setPlacePoint(null);}} />{places.map(place=><View key={place.id} style={[styles.card,{backgroundColor:p.card}]}><Text numberOfLines={1} style={{color:p.text,fontWeight:'700',fontSize:18}}>{place.name}</Text><Text style={{color:p.muted,fontSize:12}}>{place.address}</Text><View style={{flexDirection:'row',gap:10}}><View style={{flex:1}}><Button title="Go here" icon="navigate-outline" disabled={vehicleLocked} onPress={()=>{requestJourney({start:[0,0],startCurrent:true,end:place.coordinate,startLabel:'Current location',endLabel:place.address,requestedAt:Date.now()});router.navigate('/');}} /></View><IconButton label="Rename saved place" icon="pencil-outline" onPress={()=>setRename({id:place.id,name:place.name})} /><IconButton label="Delete saved place" icon="trash-outline" onPress={()=>confirmDelete(()=>deletePlace(place.id))} /></View></View>)}</>}
    {section === 'rides' && <Button title="Record trip" icon="recording-outline" disabled={vehicleLocked} onPress={()=>router.push('/offline/record-trip')} />}
    {section === 'routes' && <Button title="Import GPX to Library" icon="add-outline" secondary disabled={!ready} onPress={() => void run(async () => { const r = await pickTrack(); if (r) await save(r); })} />}
    </View>} ListFooterComponent={<View style={{ gap: 18 }}>{section === 'maps' && <>
    <Text style={{ color: p.text, fontSize: 20, fontWeight: '800' }}>Downloaded maps</Text>
    <View style={[styles.card, { backgroundColor: p.card }]}><Text style={{ color: p.text, fontWeight: '700' }}>Map region for your selected route</Text><Text style={{ color: p.muted, lineHeight: 20 }}>{Platform.OS === 'web' ? 'Downloads are available in the native app.' : !offlineEnabled ? 'Set up Stadia Maps in Settings to enable downloads.' : 'Downloads the route bounding box plus a small margin, zooms 10–14. Download on Wi-Fi; size depends on the region.'}</Text><Button title="Set up download maps" icon="settings-outline" secondary onPress={()=>router.navigate('/settings')} /><Button title={busy ? 'Creating download…' : 'Download selected region'} disabled={busy || !selected || !offlineEnabled || Platform.OS === 'web'} icon="download-outline" onPress={() => void run(async () => { setBusy(true); try { await download(selected!, () => { void refresh().catch(e => setError(e.message)); }, setError); await refresh(); } finally { setBusy(false); } })} /></View>
    {regions.map(r => <View key={r.id} style={[styles.card, { backgroundColor: p.card }]}><Text style={{ color: p.text, fontWeight: '700' }} numberOfLines={1}>{r.name}</Text><Text style={{ color: p.muted }}>{r.state} · {r.percentage.toFixed(0)}% · {(r.bytes / 1e6).toFixed(1)} MB downloaded</Text><View style={{ height: 5, backgroundColor: p.line, borderRadius: 5 }}><View style={{ height: 5, width: `${Math.min(100, r.percentage)}%`, backgroundColor: p.accent, borderRadius: 5 }} /></View><View style={{ flexDirection: 'row', gap: 10 }}>{r.state !== 'complete' && <Button title={r.state === 'active' ? 'Pause' : 'Resume'} secondary onPress={() => void run(async () => { if (r.state === 'active') await r.pack.pause(); else await resumePack(r.id); await refresh(); })} />}<IconButton label="Delete downloaded map" icon="trash-outline" onPress={() => deleteRegion(r.id)} /></View></View>)}

    <Text style={{ color: p.muted, lineHeight: 21 }}>Android uses OpenFreeMap with MapLibre. Enable Use downloadable maps in Settings to automatically use a completed region covering your current location or the whole route; otherwise iOS uses Apple Maps. Apple Maps does not expose app-managed region downloads. Offline maps contain map resources, not a routing graph. Saved-route guidance works without new route requests. Planning and rerouting require a connection; on-device route calculation is future work.</Text>
  </>}{!!error && <Text style={{color:'#C75A36'}}>{error}</Text>}</View>} /><Modal visible={placeMap} animationType="slide" onRequestClose={()=>setPlaceMap(false)}><SafeAreaView style={{flex:1,backgroundColor:p.bg}}><View style={{padding:16,flexDirection:'row',gap:12,alignItems:'center'}}><Text style={{color:p.text,flex:1,fontWeight:'700'}}>Tap the map to choose a saved place</Text><IconButton label="Close place map" icon="close" onPress={()=>setPlaceMap(false)} /></View>{placeMap && <RideMap routes={[]} selected={null} startPoint={placePoint || undefined} onPick={c=>{setPlacePoint(c);setAddress(positionLabel(c));setPlaceMap(false);}} />}</SafeAreaView></Modal><ActionMenu title="Share ride" actions={actions} onClose={()=>setActions(null)} /><Modal visible={!!rename} transparent animationType="fade" onRequestClose={()=>setRename(null)}><KeyboardAvoidingView behavior={Platform.OS==='ios' ? 'padding' : undefined} style={{flex:1,justifyContent:'center',padding:24,backgroundColor:'#00000070'}}><View style={[styles.card,{backgroundColor:p.card,width:'100%',maxWidth:500,alignSelf:'center'}]}><Text style={{color:p.text,fontWeight:'700',fontSize:20}}>Rename place</Text><Field label="Place name" value={rename?.name || ''} maxLength={120} onChangeText={name=>setRename(v=>v?{...v,name}:null)} /><Button title="Save name" icon="checkmark" disabled={!rename?.name.trim()} onPress={()=>{if(rename)renamePlace(rename.id,rename.name);setRename(null);}} /><Button title="Cancel" secondary onPress={()=>setRename(null)} /></View></KeyboardAvoidingView></Modal></SafeAreaView>;
}

function positionLabel(p: [number, number]) { return `${p[1].toFixed(5)}, ${p[0].toFixed(5)}`; }
function confirmDelete(action: () => void) { if (Platform.OS === 'web') { if (window.confirm('Delete this item from Library?')) action(); } else Alert.alert('Delete from Library?', 'This removes the local record.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: action }]); }
function recordedRoute(r: RecordedRide): Route { return { id: `preview-${r.id}`, name: r.name, kind: 'track', coordinates: r.preview, steps: [], details: {}, source: 'gpx', warnings: [] }; }
