import React,{useEffect,useState} from 'react';
import { Image,Text,View } from 'react-native';
import { Button,styles,usePalette } from './ui';
import { applyPwaUpdate,installPwa,pwaState,subscribePwa } from '../services/pwa.web';
import { useStore } from '../services/store';
export default function PwaInstallBanner(){const p=usePalette(),{vehicleLocked}=useStore(),[state,setState]=useState(pwaState),[details,setDetails]=useState(false),[error,setError]=useState('');
 useEffect(()=>subscribePwa(()=>setState(pwaState())),[]);
 const ios=typeof navigator!=='undefined' && (/iPhone|iPad|iPod/.test(navigator.userAgent) || (navigator.platform==='MacIntel' && navigator.maxTouchPoints>1));
 return <View style={[styles.card,{backgroundColor:p.card}]}><View style={{flexDirection:'row',gap:14,alignItems:'center'}}><Image source={{uri:'/pwa/icon-192.png'}} accessibilityLabel="Velunivo app icon" style={{width:56,height:56,borderRadius:13}} /><View style={{flex:1}}><Text style={{color:p.text,fontSize:20,fontWeight:'700'}}>{state.installed ? 'Velunivo is installed' : 'Install Velunivo'}</Text><Text style={{color:p.muted}}>Open directly from your Home Screen or desktop.</Text></View></View>{!state.installed && <><Button title={state.prompt ? 'Install app' : ios ? 'Add to Home Screen' : 'How to install'} icon="download-outline" onPress={()=>{if(state.prompt)void installPwa().catch(()=>setError('Installation was not completed. Try the browser’s install menu.'));else setDetails(v=>!v);}} />{details && <Text style={{color:p.text,lineHeight:22}}>{ios ? 'In Safari, open Share, choose Add to Home Screen, keep Open as Web App enabled if shown, then tap Add.' : 'Use your browser’s Install app menu. On Safari for Mac choose File → Add to Dock. Installation requires HTTPS (localhost is supported for testing).'}</Text>}</>}<Text style={{color:p.muted,lineHeight:20}}>The web app can reopen its cached app shell and local Library offline. Maps and new route searches need a connection. Keep it open for GPS navigation; background guidance and Live Activities require the native iOS app.</Text>{state.waiting && <><Button title="Update web app" icon="refresh-outline" disabled={vehicleLocked} onPress={applyPwaUpdate} /><Text style={{color:p.muted}}>A new version is ready.{vehicleLocked ? ' End your ride before updating.' : ' Reload to apply it.'}</Text></>}{!!(error || state.error) && <Text accessibilityRole="alert" style={{color:p.muted}}>{error || state.error}</Text>}</View>;
}
