import React, {useState,useRef} from 'react';
import {View,Text,ScrollView,Switch,Pressable,Platform,Linking} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {router} from 'expo-router';
import Constants from 'expo-constants';
import {Ionicons} from '@expo/vector-icons';
import {useStore} from '../services/store';
import {setMapKey,hasMapKey} from '../services/mapSettings';
import {versionTap} from '../core/developerGate';
import {settingOptions,settingsGroups} from '../core/settingsGroups';
import {Button,Field,IconButton,styles,usePalette} from './ui';
import ActivityDiagnostics from './ActivityDiagnostics';
import PwaInstallBanner from './PwaInstallBanner';
export default function SettingsScreen({section}:{section?:string}) {
  const p=usePalette(),{navigationOptions:n,updateNavigationOptions,vehicleLocked}=useStore();
  const [revealed,setRevealed]=useState(false),taps=useRef<number[]>([]),[mapKey,setKey]=useState(''),[mapStatus,setMapStatus]=useState('');
  const group=settingsGroups.find(g=>g.id===section),developer=section==='developer' && n.developerMode;
  const options=[...settingOptions,{key:'askBatteryUsage',title:'Ask for battery usage',icon:'battery-half-outline',detail:'After a saved GPS ride, ask how many percentage points of vehicle battery were used. Optional; skip if you charged en route. Three reports of at least 500 m and 1% used refine that vehicle’s future estimates.'}] as const;
  const card=(children:React.ReactNode)=><View style={[styles.card,{backgroundColor:p.card}]}>{children}</View>;
  return <SafeAreaView style={{flex:1,backgroundColor:p.bg}}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:24,gap:20,width:'100%',maxWidth:700,alignSelf:'center',paddingBottom:36}}>
    <View style={{flexDirection:'row',alignItems:'center',gap:14}}>{section && <IconButton label="Back to Settings" icon="chevron-back" onPress={()=>router.navigate('/settings')} />}<Text style={[styles.title,{color:p.text,flex:1}]}>{group?.title || (developer?'Developer Options':section?'Settings options':'Settings')}</Text></View>
    {!section && <><PwaInstallBanner />{card(settingsGroups.map(g=><Pressable key={g.id} accessibilityRole="button" accessibilityLabel={g.title} onPress={()=>router.push({pathname:'/settings/[section]',params:{section:g.id}})} style={{flexDirection:'row',gap:14,alignItems:'center',paddingVertical:12,minHeight:60}}><Ionicons name={g.icon} size={25} color={p.accent} /><View style={{flex:1,gap:4}}><Text style={{color:p.text,fontWeight:'700',fontSize:17}}>{g.title}</Text><Text style={{color:p.muted,fontSize:12,lineHeight:18}}>{g.description}</Text></View><Ionicons name="chevron-forward" size={20} color={p.muted} /></Pressable>))}
    {revealed && card(<><View style={{flexDirection:'row',alignItems:'center',gap:12}}><View style={{flex:1}}><Text style={{color:p.text,fontWeight:'700'}}>Developer Mode</Text><Text style={{color:p.muted,fontSize:12}}>Show simulation and full sensor JSON export.</Text></View><Switch accessibilityLabel="Developer Mode" value={n.developerMode} onValueChange={developerMode=>updateNavigationOptions({developerMode})} /></View>{n.developerMode && <Button title="Developer Options" icon="code-slash-outline" secondary onPress={()=>router.push('/settings/developer')} />}</>)}
    <Pressable accessibilityRole="button" accessibilityLabel="App version" onPress={()=>{const next=versionTap(taps.current,Date.now());taps.current=next.taps;if(next.revealed)setRevealed(true);}} style={{alignItems:'center',padding:18}}><Text style={{color:p.muted}}>Velunivo {Constants.expoConfig?.version || '0.1.22'}</Text></Pressable></>}
    {group && group.keys.length>0 && card(options.filter(option=>(group.keys as readonly string[]).includes(option.key)).map(option=><View key={option.key} style={{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:6}}><Ionicons name={option.icon} size={22} color={p.accent} /><View style={{flex:1,gap:4}}><Text style={{color:p.text,fontWeight:'700'}}>{option.title}</Text><Text style={{color:p.muted,fontSize:12,lineHeight:18}}>{option.detail}</Text></View><Switch disabled={option.key==='backgroundNavigation' && (vehicleLocked || Platform.OS==='web')} accessibilityLabel={option.title} value={n[option.key]} onValueChange={value=>updateNavigationOptions({[option.key]:value})} trackColor={{true:p.accent}} /></View>))}
    {section==='navigation' && card(<><Text style={{color:p.text,fontSize:18,fontWeight:'700'}}>Navigation view</Text><Button title={n.tilted?'3D perspective on':'2D flat map'} icon="layers-outline" secondary onPress={()=>updateNavigationOptions({tilted:!n.tilted})} /><Button title={n.compass?'Use device compass when available':'Use travel direction'} icon="compass-outline" secondary onPress={()=>updateNavigationOptions({compass:!n.compass})} /><Text style={{color:p.muted}}>Web follows GPS course or route direction. Device compass needs a native build and good calibration.</Text></>)}
    {section==='general' && card(<><Text style={{color:p.text,fontSize:18,fontWeight:'700'}}>Distance & speed units</Text><Button title="Kilometres · km/h" secondary={n.unit!=='km'} onPress={()=>updateNavigationOptions({unit:'km'})} /><Button title="Miles · mph" secondary={n.unit!=='mi'} onPress={()=>updateNavigationOptions({unit:'mi'})} /><Text style={{color:p.muted}}>Applies throughout the app. Vehicle range and speed inputs follow these units too.</Text></>)}
    {section==='maps' && card(<><Text style={{color:p.text,fontSize:18,fontWeight:'700'}}>Download maps setup</Text><Text style={{color:p.muted,lineHeight:20}}>Stadia Maps supports mobile offline caching with an active account and key. Its free plan may suit personal use; account terms apply. Cached maps are limited to 100 MB per device. Online maps stay key-free. Downloads do not provide offline route calculation.</Text><Button title="Manage downloaded maps" icon="download-outline" secondary onPress={()=>router.push('/offline/maps')} /><Button title="Get a Stadia Maps key" icon="globe-outline" secondary onPress={()=>void Linking.openURL('https://stadiamaps.com/').catch(()=>setMapStatus('Could not open provider website.'))} /><Field label="Stadia Maps API key" secureTextEntry autoCapitalize="none" value={mapKey} onChangeText={setKey} placeholder={hasMapKey()?'Key saved on device':'Paste your account key'} editable={Platform.OS!=='web'} /><Button title="Save map key" icon="key-outline" disabled={Platform.OS==='web' || !mapKey.trim()} onPress={()=>void setMapKey(mapKey).then(()=>{setKey('');setMapStatus('Key saved. Download your selected route region from Library → Downloaded Maps.');}).catch(e=>setMapStatus(e.message))} />{hasMapKey() && <Button title="Remove map key" icon="close" secondary onPress={()=>void setMapKey('').then(()=>setMapStatus('Key removed. Existing regions are kept.'))} />}<Text style={{color:p.muted}}>{mapStatus || (Platform.OS==='web'?'Set up downloads on iPhone or Android.':'The key is kept in device secure storage.')}</Text></>)}
    {section==='privacy' && card(<><Text style={{color:p.text,fontSize:18,fontWeight:'700'}}>Your ride data</Text><Text style={{color:p.muted,lineHeight:21}}>Recorded GPS, sensor readings and battery feedback stay on your device until you share them. Manage exports and deletion in Library → Recorded Rides. Battery feedback is used only for the same vehicle, and never reads your phone’s battery.</Text><Text style={{color:p.muted,lineHeight:21}}>Address search and route planning use Photon and Valhalla public services unless a GraphHopper server key is configured. Searches and endpoints are sent to these providers. Imported GPX stays on your device unless you explicitly plan a new route from its endpoints. Scheduled ETA never predicts traffic.</Text><Button title="Recorded Rides" icon="recording-outline" secondary onPress={()=>router.push('/offline/rides')} /></>)}
    {developer && <ActivityDiagnostics developerMode rideActive={vehicleLocked} />}{section && !group && !developer && <Text style={{color:p.muted}}>These options are unavailable.</Text>}
  </ScrollView></SafeAreaView>;
}
