import React, { useState } from 'react';
import { Image, Linking, Platform, ScrollView, Text, View, Pressable } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router, useLocalSearchParams } from 'expo-router';
import { Button, Field, IconButton, styles, usePalette } from '../../../components/ui';
import { VehicleIcon } from '../../../components/VehicleSelector';
import { useStore } from '../../../services/store';
import { pickVehiclePhoto } from '../../../services/files';
import { photoUri, deletePhoto } from '../../../services/vehiclePhotos';
import { rangeKm, rangeValue } from '../../../core/vehicles';
function NumberField({ label, value, min, max, onSave }: { label: string; value: number; min: number; max: number; onSave(v: number): void }) {
  const [text, setText] = useState(String(value)), [error, setError] = useState('');
  return <View style={{ gap: 4 }}><Field label={label} value={text} onChangeText={setText} keyboardType="decimal-pad" onBlur={() => { const v = Number(text.replace(',', '.')); if (!text.trim() || !Number.isFinite(v) || v < min || v > max) { setError(`Choose ${min}–${max}.`); setText(String(value)); } else { setError(''); if (v !== value) onSave(v); } }} />{!!error && <Text style={{ color: '#C75A36' }}>{error}</Text>}</View>;
}
export default function VehicleOptions() {
  const { id, section } = useLocalSearchParams<{ id: string; section: string }>(), p = usePalette(), { vehicles, updateProfile, vehicleLocked, navigationOptions } = useStore();
  const v = vehicles.find(v => v.id === id), [error, setError] = useState(''), [loading, setLoading] = useState(false);
  const unit = navigationOptions.unit, factor = unit === 'mi' ? 1.609344 : 1, speedUnit = unit === 'mi' ? 'MPH' : 'KM/H';
  const title = ({ identity: 'Name & speed limits', range: 'Range & battery', appearance: 'Icon & pictures', tuning: 'ETA tuning' } as Record<string, string>)[section] || 'Vehicle options';
  const update = (changes: Parameters<typeof updateProfile>[0]) => updateProfile(changes, id);
  return <SafeAreaView style={{ flex: 1, backgroundColor: p.bg }}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ padding: 24, gap: 18, width: '100%', maxWidth: 700, alignSelf: 'center', paddingBottom: 90 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}><IconButton label="Back to vehicle" icon="chevron-back" onPress={() => router.replace(`/scooter/${id}`)} /><Text style={{ color: p.text, fontSize: 25, fontWeight: '800', flex: 1 }}>{title}</Text></View>{v && <View pointerEvents={vehicleLocked ? 'none' : 'auto'} style={{ gap: 18, opacity: vehicleLocked ? .5 : 1 }}>
    {section === 'identity' && <><Field label="VEHICLE NAME" maxLength={80} value={v.name} onChangeText={name => update({ name })} />{(['maxSpeed', 'ridingLimit'] as const).map(key => <NumberField key={`${key}-${v[key]}-${unit}`} label={`${key === 'maxSpeed' ? 'HARDWARE MAXIMUM' : 'LOCAL RIDING LIMIT'} · ${speedUnit}`} value={Number((v[key] / factor).toFixed(2))} min={Number((1 / factor).toFixed(2))} max={Number((60 / factor).toFixed(2))} onSave={n => update({ [key]: Math.max(1, Math.min(60, n * factor)) })} />)}<Text style={{ color: p.muted }}>The riding cap is the lower of these limits. Check local rules and vehicle eligibility. New scooters start at 25 km/h.</Text></>}
    {section === 'range' && <><NumberField key={`${v.rangeKm}-${unit}`} label={`FULL-CHARGE RANGE · ${unit === 'mi' ? 'MILES' : 'KM'}`} value={v.rangeKm ? Number(rangeValue(v.rangeKm, unit).toFixed(2)) : 0} min={0} max={Number((10000 / factor).toFixed(2))} onSave={n => update({ rangeKm: n ? rangeKm(n, unit) : null })} /><Text style={{ color: p.muted }}>Use 0 for unknown. Estimated trip battery use is distance ÷ full-charge range, not a live battery measurement.</Text></>}
    {section === 'tuning' && <>{([{ key: 'cruiseFactor', label: 'CRUISE FACTOR', min: .2, max: 1 }, { key: 'acceleration', label: 'ACCELERATION · M/S²', min: .1, max: 4 }, { key: 'stopDelay', label: 'MANEUVER DELAY · SECONDS', min: 0, max: 120 }] as const).map(field => <NumberField key={`${field.key}-${v[field.key]}`} label={field.label} value={v[field.key]} min={field.min} max={field.max} onSave={n => update({ [field.key]: n })} />)}<Text style={{ color: p.muted }}>ETA models slower roads, cruise speed and maneuver delays. Traffic, hills and weather are not predicted.</Text></>}
    {section === 'appearance' && <><View style={[styles.card, { backgroundColor: p.card, alignItems: 'center' }]}><VehicleIcon vehicle={v} size={150} /><Text style={{ color: p.muted }}>Current icon or picture</Text></View><View style={{ flexDirection: 'row', gap: 8, flexWrap: 'wrap' }}>{['🛴', '🚲', '⚡', '🛵', '🚴', '🔋'].map(icon => <Pressable accessibilityRole="button" accessibilityLabel={`Use ${icon} icon`} key={icon} onPress={() => update({ icon, photo: null })} style={{ padding: 14, backgroundColor: p.card, borderRadius: 16 }}><Text style={{ fontSize: 26 }}>{icon}</Text></Pressable>)}</View><Field label="CUSTOM ICON · EMOJI OR SYMBOL" value={v.icon} maxLength={32} onChangeText={icon => update({ icon: icon || (v.kind === 'ebike' ? '🚲' : '🛴'), photo: null })} /><Button title={loading ? 'Preparing picture…' : Platform.OS === 'web' ? 'Choose picture' : 'Choose from photo library'} icon="image-outline" disabled={loading} secondary onPress={() => { setError(''); setLoading(true); void pickVehiclePhoto().then(photo => { if (photo) update({ photo, photos: Array.from(new Set([...(v.photos || []), ...(v.photo ? [v.photo] : []), photo])) }); }).catch(e => setError(e.message)).finally(() => setLoading(false)); }} />{!!v.photos?.length && <><Text style={{ color: p.text, fontWeight: '700' }}>Saved pictures · tap to use</Text><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 14 }}>{v.photos.map(photo => <View key={photo} style={{ gap: 6, width: 108 }}><Pressable accessibilityRole="button" accessibilityLabel="Use saved vehicle picture" accessibilityState={{ selected: v.photo === photo }} onPress={() => update({ photo })}><Image source={{ uri: photoUri(photo) }} style={{ width: 108, height: 108, borderRadius: 16, borderWidth: 3, borderColor: v.photo === photo ? p.accent : p.line }} /></Pressable><IconButton label="Delete saved vehicle picture" icon="trash-outline" onPress={() => { update({ photos: v.photos!.filter(x => x !== photo), photo: v.photo === photo ? null : v.photo }); deletePhoto(photo); }} /></View>)}</View></>}<Button title="Browse public vehicle pictures" icon="globe-outline" secondary onPress={() => void Linking.openURL(`https://commons.wikimedia.org/w/index.php?search=${v.kind === 'ebike' ? 'electric+bicycle' : 'electric+kick+scooter'}&title=Special:MediaSearch&type=image`).catch(e => setError(e.message))} /><Text style={{ color: p.muted }}>Photos stay on this device until removed. Check licences and attribution for public pictures.</Text></>}
  </View>}{vehicleLocked && <Text style={{ color: p.muted }}>Finish your ride to edit this vehicle.</Text>}{!!error && <Text accessibilityRole="alert" style={{ color: '#C75A36' }}>{error}</Text>}</ScrollView></SafeAreaView>;
}
